### ISSUE TITLE
" SFx Migration Tracker

### ISSUE THREAD

**Issue by JonoRicci** [JonoRicci/api-test-repo#13]
# SignalFx Migration Tracker

## Overview

Please see the following docs:

* [Master Sheet of SignalFx Customer Adoption](https://docs.google.com/spreadsheets/d/1FXOctWCJbhtRwYPlXsT8lQGMmtKpYRmGYsyN1bWvUDA/)
* [Parent Document of Splunk to SignalFx Migration](https://cloudreach.jira.com/wiki/spaces/CO/pages/1732247656/WIP+AIS+CoreOps+-+Splunk+to+SignalFx+Migration+Guide)
* [GitHub Epic of SignalFx Migration](https://github.com/cloudreach-coreops/CoreOps/issues/69)

## Tracker

Complete the checklist as you proceed.

### Pre-Migration

* [ ] Complete Access Pre-requisites
* [ ] Scope Customer Accounts
  * [ ] Gather existing recurring / future maintenance windows
  * [ ] Gather customer custom alarms
  * [ ] Gather customer custom thresholds on alarms
* [ ] Confirm whether re-onboarding to Cloud Core 2.5

### Migration

* [ ] Complete [Splunk to SignalFx Migration](https://cloudreach.jira.com/wiki/spaces/CO/pages/1622114368/Splunk+to+SignalFx+Migration)
* [ ] Complete [SignalFx Setup](https://cloudreach.jira.com/wiki/spaces/CO/pages/1632764727/Signalfx+Setup)
* [ ] Alert Logic Log Ingestion set up

### Post-Migration

* [ ] Validate SFx monitoring
* [ ] Monitor PagerDuty and help resolve alarms from Migration
